FROM python:3.11-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1  
ENV PYTHONUNBUFFERED=1

# Set the working directory in the container
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender1 \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Copy only requirements.txt first to leverage Docker caching
COPY requirements.txt /app/

# Create and activate the virtual environment
RUN python3 -m venv /app/venv

# Install dependencies into the virtual environment
RUN /app/venv/bin/pip install --no-cache-dir --upgrade pip && \
    /app/venv/bin/pip install --no-cache-dir -r /app/requirements_clean.txt

# Copy the rest of the application code
COPY . /app/

# Copy the .env file to the root directory
COPY .env /app/.env

# Expose a port (adjust as necessary for your app)
EXPOSE 5003

# Set environment variable for the virtual environment to use
ENV PATH="/app/venv/bin:$PATH"

# Command to run the application (adjust as necessary)
CMD ["python", "app.py"]
